<a href="https://colab.research.google.com/github/minhquang1206/THToanCaoCap/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

bai 1:


In [3]:
import math

In [1]:
x = 3
print(x)

3


In [6]:
x = math.sqrt(1+x)
print(x)

1.6528916502810695


In [7]:
x = math.sqrt(1+x)
print(x)

1.6287699807772333


In [8]:
x = math.sqrt(1+x)
print(x)

1.621348198499395


bai 2:

In [9]:
import math
x = 3
lap = 1
while(x != math.sqrt(x+1)):
  x = math.sqrt(x+1)
  lap = lap + 1

In [10]:
x

1.618033988749895

In [11]:
lap

32

bai 3

In [12]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

bai 4:

In [13]:
import numpy as np
v1 = np.array([1.,2.,3.])
v2 = np.array([2.,2.,0.])
v3 = v1 + v2
v3

array([3., 4., 3.])

In [14]:
3* v1 + 2*v2

array([ 7., 10.,  9.])

In [15]:
[1,2,3] + [2,1,0]

[1, 2, 3, 2, 1, 0]

In [16]:
3*[1,2,3] + 2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [17]:
v4 = np.hstack([v1,v2])

In [18]:
np.dot(v1,v2)

6.0

In [19]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [20]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])